### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by JamieWhite** [wibosco/CoreDataServices#21]
You appear to have arbitrarily dropped iOS 9 support. Is there a reason why?

The project still builds with iOS 9 so it should be supported at least until a point where you're using iOS 10+ APIs

**Comment by wibosco** [comment]
Hey @JamieWhite, I'm currently working on a refactoring to introduce the `NSPersistentContainer` as a part of wider refactoring to introduce a more sophisticated migration system. 

Are you using the project directly from head? Pointing at `3.2.2` should continue to provide iOS9 support.

**Comment by JamieWhite** [comment]
The main issue is Xcode complains at your pod needing to be updated for swift4. You’ve recently added swift 4 build support so it’d be good to have a version that compiles for iOS 9 before you move to iOS 10 apis

**Comment by wibosco** [comment]
Ah, excellent point - small steps 😉. I'll revert the change (dropping iOS9) and release `4.0.0`

**Comment by wibosco** [comment]
@JamieWhite I've released `4.0.0` of this project which updates it to use `swift 4` and keeps support `iOS 9`.

Let me know if you have any trouble
